FROM gradle:6.8.3-jdk11 AS build

WORKDIR /home/gradle/src
COPY build.gradle.kts settings.gradle.kts /home/gradle/src/
RUN gradle clean build --no-daemon > /dev/null 2>&1 || true
COPY ./ /home/gradle/src/
RUN gradle build --no-daemon -x test

FROM openjdk:11-jre-slim
EXPOSE 8080
RUN mkdir /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/spring-boot-application.jar
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=production","/app/spring-boot-application.jar"]